version: 2
jobs:
  build:
    working_directory: ~/play/google_search_automation
    docker:
      - image: circleci/node:4.8.2-pb
    steps:
      - checkout
      - run:
          name: update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency
